// <auto-generated />
using Core.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.Entity.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20190613130332_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Entity.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "a2bf1adc-3dfc-4939-aa9a-3320e4fb9600",
                            Title = "本教程由Siegrain倾情奉献 :)"
                        },
                        new
                        {
                            Id = 2,
                            Content = "6c6286bf-626f-4de9-8300-7caca71851a1",
                            Title = "感谢大家关注~"
                        },
                        new
                        {
                            Id = 3,
                            Content = "13da4743-0b63-413a-8a16-d5bda43cafca",
                            Title = "博客地址为 http://siegrain.wang"
                        },
                        new
                        {
                            Id = 4,
                            Content = "9b439e03-47b0-40ea-a988-aa26e6d75916",
                            Title = "本教程Github地址为 https://github.com/Seanwong933/.NET-Core-with-Docker"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
