version: '3.3'
services:
  coreapi:
    container_name: coreapi
    image: siegrainwong/coreapi:latest
    ports:
      - 5000:5000
    depends_on:
      - sqlserver
    links:
      - sqlserver
    volumes:
      - ./Core.API/appsettings.docker.json:/app/appsettings.json:ro
    restart: always
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      SA_PASSWORD: 'NetCore123!@#'
    volumes:
      - coredata:/var/opt/mssql # <--
    ports:
      - 1433
volumes:
  coredata: # <--